### PR TITLE
I have added the last command which users are normally not much aware…

### PR DESCRIPTION
**Pull request by uddeshyatyagi**
… about,hope this will help the beginners to learn something new and different

### CODE REVIEW

**Comment by uddeshyatyagi** [comment]
@rajeev29five , I have changed command no. 11 to 14,have replaced #> with `` and have added the output of the commands as well.
So please review.
Thanks

**Comment by rajeev29five** [comment]
> @rajeev29five , I have changed command no. 11 to 14,have replaced #> with `` and have added the output of the commands as well.
> So please review.
> Thanks

Your output part is not rendering properly because of extra ```. Please remove extra ```` from where ever required to achieve expected rendering.  

Look at the screenshots 

Your output with extra ```
youroutput

Expected output after removing extra ```
expected

**Comment by uddeshyatyagi** [comment]
If anything still not working then please inform me

**Comment by rajeev29five** [comment]
> If anything still not working then please inform me

1. Output is still not rendering properly.

2. Replace all "uddeshya" with "username" 

3. Do not include word "Output : "  in output section.

Use below code example template to properly render output.

\<p class="terminal">Terminal</p>\```
username@localhost:~/basiccommands$ last -5

Copy and paste your output here, do not include extra ticks or anything else.
\```
\<br>

```
```

Your output : 
youroutput

Expected output:
expectedoutput

**Comment by uddeshyatyagi** [comment]
@rajeev29five please review the changes

**Comment by rajeev29five** [comment]
> @rajeev29five please review the changes

This one is good. Just replace all the word "uddeshya" with the word "username" in the output, so that the output is more generic.

**Comment by uddeshyatyagi** [comment]
Hope all is good now!Please review.

**Comment by rajeev29five** [comment]
> Hope all is good now!Please review.

Great work! I have deployed the changes you should be able to see it here  https://rajeev29five.github.io/command-line.html

**Comment by uddeshyatyagi** [comment]
Thank you :-P

**Pull request merged**
